# Generated by Django 4.2.24 on 2025-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
