# Generated by Django 4.2.24 on 2025-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
