# Generated by Django 5.2.5 on 2025-09-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_ui.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_ui.stop')),
            ],
        ),
    ]
