# Generated by Django 5.2.5 on 2025-09-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0004_arrivallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_eta', models.FloatField(help_text='ETA in minutes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_ui.bus')),
            ],
        ),
    ]
